name: publisher
description: Tool for release automation of cross-platform apps
version: 0.1.0
homepage: https://github.com/methodpark/dart-publisher
repository: https://github.com/methodpark/dart-publisher
issue_tracker: https://github.com/methodpark/dart-publisher/issues

executables:
  publisher:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  _discoveryapis_commons: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  dartdoc: ^4.0.0
